
stages:
  - build
  - deploy
 
docker_build_backend:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t backend backend
    - docker tag backend azizul2go/two-tier-backend-image:latest
    - echo "$DOCKERHUB_PASSWORD" | docker login -u azizul2go --password-stdin
    - docker push azizul2go/two-tier-backend-image:latest
 
docker_build_frontend:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t frontend frontend
    - docker tag frontend azizul2go/two-tier-frontend-image:v2
    - echo "$DOCKERHUB_PASSWORD" | docker login -u azizul2go --password-stdin
    - docker push azizul2go/two-tier-frontend-image:v2
 
deploy_backend_k8s:
  stage: deploy
  image: bearengineer/awscli-kubectl
  script:
    - aws eks update-kubeconfig --region us-east-1 --name june-24-eks
    - kubectl apply -f deployments/backend-deployment.yaml -f deployments/backend-service.yaml
    - kubectl rollout restart -f deployments/backend-deployment.yaml
 
deploy_frontend_k8s:
  stage: deploy
  image: bearengineer/awscli-kubectl
  script:
    - aws eks update-kubeconfig --region us-east-1 --name june-24-eks
    - kubectl apply -f deployments/frontend-deployment.yaml -f deployments/frontend-service.yaml
    - kubectl rollout restart -f deployments/frontend-deployment.yaml
